description: "Production profile for VMs with bridged networking and 50GiB root disk"
devices:
  root:
    path: /
    pool: incus-instances
    type: disk
    size: 50GiB
  eth0:
    name: eth0
    network: phys-br
    type: nic
config:
  boot.autostart: true
  security.privileged: false
  security.protection.delete: true