---
- name: Pre-Processing -- Generate random salt for password.
  ansible.builtin.shell: |
    set -o pipefail &&
    tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 16 || true
  args:
    executable: /bin/bash
  register: random_salt
  no_log: true
  changed_when: false
  failed_when: random_salt.rc != 0 and random_salt.rc != 141  # 141 is the exit code for head when it reaches EOF

- name: Pre-Processing -- Generate encrypted password for cloud-init with custom salt and rounds
  ansible.builtin.shell: |
    mkpasswd -m sha-512 -R 65536 -S {{ random_salt.stdout }} '{{ generate_password_input }}'
  register: encrypted_password
  no_log: true
  changed_when: false

- name: Pre-Processing -- Set password fact
  ansible.builtin.set_fact:
    generated_lx_password: "{{ encrypted_password.stdout }}"
  no_log: true
