---
- name: Check if volume group exists
  ansible.builtin.command: vgdisplay {{ param_tasks_vgname }}
  register: vg_exists
  changed_when: false
  failed_when: false

- name: Fail if volume group does not exist
  ansible.builtin.fail:
    msg: "Volume group {{ param_tasks_vgname }} does not exist. Create it first."
  when: vg_exists.rc != 0

- name: Check if partition exists
  community.general.parted:
    device: "{{ param_tasks_partdata.device }}"
    state: info
    unit: "GiB"
  register: device_info
  changed_when: false

- name: Create or resize partition
  community.general.parted:
    device: "{{ param_tasks_partdata.device }}"
    number: "{{ param_tasks_partdata.partition_nr }}"
    state: present
    part_type: primary
    part_start: "{{ device_info.partitions[-1].end | default('0%') }}"
    part_end: "{{ (param_tasks_partdata.size | regex_replace('G$', 'GiB')) if param_tasks_partdata.size != 'all' else '100%' }}"
    resize: true
  register: partition_result
  when: >
    (device_info.partitions | default([]) | length == 0) or
    (device_info.partitions | selectattr('num', 'equalto', param_tasks_partdata.partition_nr | int) | list | length == 0)
  changed_when: partition_result is changed

- name: Inform kernel about partition table changes
  ansible.builtin.command: partprobe
  when: partition_result is changed
  changed_when: partition_result is changed

# Use lvg module to manage physical volumes and volume group
- name: Manage physical volume and volume group
  community.general.lvg:
    vg: "{{ param_tasks_vgname }}"
    pvs: "{{ param_tasks_partdata.device }}{{ param_tasks_partdata.partition_nr }}"
    pvresize: true
    state: present
  register: lvg_result

# Create logical volume using lvol module
- name: Create logical volume for images if specified
  community.general.lvol:
    vg: "{{ param_tasks_vgname }}"
    lv: "{{ param_tasks_lvname }}"
    size: "{{ param_tasks_partdata.size }}"
    force: false
    shrink: false
  register: lv_images_result
  ignore_errors: true

- name: Display error for images volume creation (if any)
  ansible.builtin.debug:
    msg: "Failed to create logical volume for images: {{ lv_images_result.msg }}"
  when:
    - lv_images_result is defined
    - lv_images_result.failed is defined
    - lv_images_result.failed
