---
- name: Gather facts about LVM configuration
  ansible.builtin.setup:
    gather_subset:
      - hardware
  register: system_facts

- name: Check volume group existence
  community.general.lvg:
    vg: "{{ param_volume_group_name }}"
    state: present
  check_mode: true
  register: vg_check
  failed_when: false
  changed_when: false

- name: Fail if volume group does not exist
  ansible.builtin.fail:
    msg: "Volume group {{ param_volume_group_name }} does not exist."
  when: vg_check is failed

- name: Find host_config entry for this host
  ansible.builtin.set_fact:
    host_config_entry: "{{ item }}"
  loop: "{{ host_configs | default([]) }}"
  when: item.name == param_host_config_name

- name: Set selected disk configuration from the host_config entry
  ansible.builtin.set_fact:
    selected_disk_cfg: "{{ host_config_entry.virtual_disk_config | default({}) }}"

- name: Fail if selected disk config is missing
  ansible.builtin.fail:
    msg: "No virtual_disk_config found for host_config_name {{ param_host_config_name }}"
  when: selected_disk_cfg is not defined or selected_disk_cfg | length == 0

- name: Now validate if all LVM thin pools defined in the disk config are present on the target machine.
  ansible.builtin.shell: |
    set -o pipefail
    lvs --noheadings -o lv_name,lv_attr {{ param_volume_group_name }} | grep "{{ item.key }}" | grep "t"
  args:
    executable: /bin/bash
  register: thin_pool_check
  failed_when: false
  changed_when: false
  loop: "{{ selected_disk_cfg.volume_group_volumes | dict2items }}"

- name: Check if any thin pools are missing
  ansible.builtin.set_fact:
    missing_thin_pools: "{{ thin_pool_check.results | selectattr('rc', 'ne', 0) | list | length > 0 }}"

- name: Set overall validation result (only checking thin pools for Incus)
  ansible.builtin.set_fact:
    lvm_changes_required: "{{ missing_thin_pools }}"

- name: Display LVM validation results
  ansible.builtin.debug:
    msg: "{{ 'LVM thin pool configuration does not match!' if lvm_changes_required else 'LVM thin pools as expected!' }}"

- name: Display detailed results if validation fails
  ansible.builtin.debug:
    msg: |
      Missing thin pools: {{ thin_pool_check.results | selectattr('rc', 'ne', 0) | map(attribute='item.key') | list }}
      Note: Incus will manage thin volumes within these pools automatically.
  when: lvm_changes_required | bool

- name: Fail if LVM changes are required
  ansible.builtin.fail:
    msg: "Invalid LVM configuration on target host"
  when: lvm_changes_required | bool
