- name: Update apt cache {{ inventory_hostname }}
  ansible.builtin.apt:
    update_cache: true
  register: apt_update_result

- name: Upgrade packages {{ inventory_hostname }}
  ansible.builtin.apt:
    upgrade: "safe"
    force_apt_get: true
    autoremove: true
  register: apt_upgrade_result

- name: Fail if upgrade fails {{ inventory_hostname }}
  ansible.builtin.fail:
    msg: "Failed to upgrade Ubuntu packages"
  when: apt_upgrade_result is failed
