---
- name: Baseline for each Proxmox node
  hosts: all
  become: true
  gather_facts: false

  # This playbook uses global Infra-As-Code configuration variables for Proxmox hosts, only.
  vars:
    pve_root_user: "{{ root_user }}"
    pve_root_publickey: "{{ publickey_root }}"
    pve_repo_suite: "{{ repo_suites }}"
  tasks:
    - name: Set the SSH user name in case it is not the default.
      ansible.builtin.set_fact:
        ansible_user: "{{ pve_root_user }}"

    - name: Write variables for debugging
      ansible.builtin.debug:
        msg: |
          Root user: {{ pve_root_user }}
          Public Key: {{ pve_root_publickey }}
          Repo Suite: {{ pve_repo_suite }}

    - name: Deactive Enterprise Repo - Rename pve-enterprise.list to pve-enterprise.list.bak
      ansible.builtin.command:
        cmd: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
        removes: /etc/apt/sources.list.d/pve-enterprise.list

    - name: Deactivate Enterprise Repo - Rename ceph.list to ceph.list.bak
      ansible.builtin.command:
        cmd: mv /etc/apt/sources.list.d/ceph.list /etc/apt/sources.list.d/ceph.list.bak
        removes: /etc/apt/sources.list.d/ceph.list

    - name: Activate the community repository for non-commercial use (exists on all Proxmox installations).
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: "deb http://download.proxmox.com/debian/pve {{ pve_repo_suite }} pve-no-subscription"
        create: false

    - name: Create script to deactivate subscription warning
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          sed -Ezi.bak "s/(Ext.Msg.show\(\{\s+title: gettext\('No valid sub)/void\(\{ \/\/\1/g" \
          /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && \
          systemctl restart pveproxy.service
        dest: /usr/local/bin/remove_proxmox_subscription_warning.sh
        mode: '0755'
      register: script_created

    - name: Create cron-job to continuously de-activate subscription warning as it will re-appear after updates
      ansible.builtin.cron:
        name: "De-activate Proxmox subscription warning"
        minute: 0
        hour: 8
        job: "/usr/local/bin/remove_proxmox_subscription_warning.sh"

    - name: De-activate the subscription warning now.
      ansible.builtin.command:
        cmd: /usr/local/bin/remove_proxmox_subscription_warning.sh
      changed_when: false

    - name: Add the RSA public key for the root-user.
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ pve_root_publickey }}"

    - name: Deactivate SSH Login via Password.
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Activate PCI passthrough through IOMMU activation in GRUB.
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"'
      notify: Update GRUB

    - name: Activate IOMMU kernel configuration for PCI passthrough.
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: 'vfio vfio_iommu_type1 vfio_pci'
        state: present

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Update GRUB
      ansible.builtin.command:
        cmd: update-grub
      notify: Restart Host
      changed_when: true

    - name: Restart Host
      ansible.builtin.reboot:
        reboot_timeout: 300
