---
- name: Setup Proxmox SSL and Multi-factor Authentication.
  hosts: all
  become: true
  remote_user: "{{ root_user }}"

  tasks:
    - name: Install required TOTP tools locally.
      local_action:
        module: apt
        name: "oathtool"
        state: present

    - name: Generate a new TOTP secret for the root user.
      delegate_to: localhost
      ansible.builtin.command:
        module: command
        cmd: "oathtool --totp --base32 --length=32 --random --verbose"
      register: totp_secret

    - name: Set the TOTP fact for the current session.
      set_fact:
        totp_secret: "{{ totp_secret.stdout.strip() }}"
