Vagrant.configure("2") do |config|

  # Ubuntu 22.04 box for VMWare
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/ubuntu2204/versions/4.2.14/providers/vmware_desktop.box"
  config.vm.disk :disk, name: "osdisk", size: "30GB"
  config.ssh.insert_key = false

  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "3"
  end

  # In VMWare the NAT adapter is added by default, but I want the bridged adapter to be the first one
  # Add VMnet1 (Host-Only) as a second adapter with a private, static IP.
  config.vm.network "private_network", ip: "192.168.56.4", :adapter => 2, :network_name => "VMnet10"

  # Update the OS after provisioning
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
  SHELL

end