---
- name: Host setup for bare-metal servers running Incus.
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    param_root_user_name: "{{ root_user }}"
    param_root_user_fullname: "{{ root_user_fullname }}"
    param_root_user_password_clear: "{{ lookup('env', root_user_password_env) }}"
    param_root_user_publickey: "{{ root_user_publickey }}"
    param_iso_source_url: "{{ iso_source_url }}"
    param_iso_source_path: "{{ lookup('env', 'HOME') }}{{ iso_source_path }}"
    param_iso_destination_path: "{{ lookup('env', 'HOME') }}{{ iso_destination_path }}"
    param_iso_working_path: "{{ lookup('env', 'HOME') }}{{ iso_working_path }}"
    param_volume_group_name: "{{ volume_group_name }}"
    param_minimum_packages: "{{ minimum_packages }}"

  tasks:
    - name: Pre-requisites -- Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - whois  # Contains mkpasswd utility
          - xorriso
          - isolinux
          - p7zip-full
          - genisoimage
        state: present
        update_cache: true

    - name: Pre-requisites -- Ensure the ~/iso directory exists
      ansible.builtin.file:
        path: "{{ param_iso_destination_path | expanduser }}"
        state: directory
        mode: '0755'

    - name: Pre-requisites -- Download Ubuntu ISO if not already present
      ansible.builtin.get_url:
        url: "{{ param_iso_source_url }}"
        dest: "{{ param_iso_source_path }}"
        mode: '0644'
        timeout: 3600
      register: download_result
      changed_when: download_result.changed

    - name: Pre-Processing -- Generate random hostname
      ansible.builtin.shell: |
        set -o pipefail &&
        tr -dc 'a-z0-9' < /dev/urandom | head -c 8
      args:
        executable: /bin/bash
      register: random_hostname
      changed_when: false
      failed_when: random_hostname.rc != 0 and random_hostname.rc != 141  # 141 is the exit code for head when it reaches EOF

    - name: Pre-Processing -- Set hostname fact
      ansible.builtin.set_fact:
        param_random_hostname: "host-{{ random_hostname.stdout }}"

    - name: Pre-Processing -- Set variable for password generation task.
      ansible.builtin.set_fact:
        generate_password_input: "{{ param_root_user_password_clear | default('') }}"
      no_log: true

    - name: Pre-Processing -- Generate Linux password with input
      ansible.builtin.include_tasks:
        file: ../tasks/generate_lx_passwd.yaml

    - name: Pre-Processing -- Set password fact
      ansible.builtin.set_fact:
        param_root_user_password: "{{ generated_lx_password }}"
      no_log: true

    - name: Pre-Processing -- Create working directory
      ansible.builtin.file:
        path: "{{ param_iso_working_path }}"
        state: directory
        mode: '0755'

    - name: Processing -- Extract ISO using xorriso including the boot partition
      ansible.builtin.command:
        cmd: >
          xorriso -osirrox on -indev {{ param_iso_source_path }}
          -extract_boot_images "{{ param_iso_working_path }}/bootpart" -extract / {{ param_iso_working_path }}
      args:
        creates: "{{ param_iso_working_path }}/bootpart"
      register: extract_result

    - name: Processing -- Create autoinstall directory in ISO
      ansible.builtin.file:
        path: "{{ param_iso_working_path }}/autoinstall"
        state: directory
        mode: '0755'

    - name: Validation -- Ensure each incus host has a disk_config defined
      ansible.builtin.fail:
        msg: "Inventory host {{ item }} is missing a 'disk_config' definition; please add one."
      when: (hostvars[item].disk_config is not defined) or (hostvars[item].disk_config | length == 0)
      loop: "{{ groups['incus'] | default([]) }}"

    - name: Processing -- Process each server's disk configuration
      ansible.builtin.include_tasks: host-incus-image-process-disk-tasks.yml
      loop: "{{ groups['incus'] | default([]) }}"
      loop_control:
        loop_var: incus_host
        label: "{{ incus_host }}"
      vars:
        disk_config: "{{ hostvars[incus_host].disk_config }}"
        param_hostname: "{{ hostvars[incus_host].hostname | default(param_random_hostname) }}"
