main_wifi_adapter: wlan0
main_wifi_ip_address: 192.168.1.111
edge_wifi_adapter: wlan1
edge_local_wifi_name: edgewifiname
edge_wifi_ip_address: 192.168.2.1
edge_wifi_ip_netmask: 255.255.255.0
edge_wifi_dhcp_dns:
  - 192.168.1.1
  - 8.8.8.8
edge_wifi_dhcp_range: 192.168.1.50,192.168.1.150,12h
edge_wifi_allowed_ports:
  - "80"
  - "443"
  - "67"
  - "68"
  - "53"
edge_node_ssh_port: "22"