---
- name: Ensure global machine pre-requisites are met
  import_playbook: bootstrap-machines.yaml

- name: Configure Raspberry Pi Edge with bridged WiFi
  hosts: "{{ target_host }}"
  become: true
  gather_facts: false
  remote_user: "{{ lookup('env', 'USE_SSH_USER_NAME') }}"

  vars:
    target_host: edgepi
    edge_config: ../configs/pi-edge-config.yaml

  # First, ensure the pre-requisites are met
  pre_tasks:
    # First, make sure the environment variable for SSH access to the nodes is present.
    - include_tasks: ../tasklib/checkuserenv-tasks.yaml

  # Execute the main configuration flow.
  tasks:
    - name: Include pi-edge configuration settings
      include_vars: "{{ edge_config }}"

    - name: Pre-Checks - Check if the USE_WIFI_PASSWORD environment variable is set
      vars:
        env_var_name: "USE_WIFI_PASSWORD"
      assert:
        that:
          - "lookup('env','{{ env_var_name }}')"
        fail_msg: "Please set the {{ env_var_name }} environment variable before executing this playbook!"

    - name: Pre-Checks - Check if backup for sysctl.conf.default exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/sysctl.conf.default"
      register: sysctl_conf_default_file

    - name: Install additional pre-requisites for WiFi bridging
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - hostapd
        - dnsmasq
        - wpasupplicant

    - name: Clean-Up - Restore original sysctl.conf (if backup exists)
      copy:
        src: "{{ lookup('env', 'HOME') }}/sysctl.conf.default"
        dest: /etc/sysctl.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      when: sysctl_conf_default_file.stat.exists

    - name: Clean-Up - Edge-Wifi clean existing firewall rules
      command: ufw --force reset
      ignore_errors: true
      changed_when: command.rc == 0
      register: cleanupresult

    - name: Clean-Up - Edge WiFi clean existing nftables rules
      command: nft flush ruleset
      ignore_errors: true
      changed_when: command.rc == 0
      register: cleanupresult

    - name: Clean-Up - Stop hostapd service
      service:
        name: hostapd
        state: stopped
        enabled: false

    - name: Clean-Up - Stop dnsmasq service
      service:
        name: dnsmasq
        state: stopped
        enabled: false

    - name: Clean-Up - Remove local WiFi configuration using USB adapter
      command: iwconfig {{ edge_wifi_adapter }} essid "" mode managed
      ignore_errors: true
      changed_when: command.rc == 0
      register: cleanupresult

    - name: Clean-Up - Reset IP address for USB adapter
      command: ifconfig {{ edge_wifi_adapter }} 0.0.0.0 down
      ignore_errors: true
      changed_when: command.rc == 0
      register: cleanupresult

    - name: System Config - Enable IP forwarding (current session)
      command: sysctl -w net.ipv4.ip_forward=1
      ignore_errors: true
      changed_when: command.rc == 0
      register: systemconfigresult

    - name: System Config - Backup sysctl.conf.default in the user's home directory
      copy:
        src: /etc/sysctl.conf
        dest: "{{ lookup('env', 'HOME') }}/sysctl.conf.default"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
      when: not sysctl_conf_default_file.stat.exists

    - name: System Config - Enable IP forwarding (permanent in sysctl.conf)
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward=1"
        state: present
      register: ip_forwarding_result
      changed_when: ip_forwarding_result.changed

    - name: Edge WiFi - Create local WiFi using USB adapter
      command: iwconfig {{ edge_wifi_adapter }} essid {{ edge_local_wifi_name }} mode ad-hoc
      changed_when: command.rc == 0

    - name: Edge WiFi - Set IP address for USB adapter
      command: ifconfig {{ edge_wifi_adapter }} {{ edge_wifi_ip_address }} netmask {{ edge_wifi_ip_netmask }}
      changed_when: command.rc == 0

    - name: Edge WiFi - Configure nftables for HTTP(S) forwarding
      command: nft add rule ip nat prerouting iifname {{ edge_wifi_adapter }} tcp dport {{ item }} dnat to {{ main_wifi_ip_address }}
      loop: "{{ edge_wifi_forwarded_ports }}"
      register: nftables_check_result
      changed_when: nftables_check_result.rc != 0

    - name: Edge WiFi - Save nftables rules
      command: nft list ruleset > /etc/nftables.conf
      changed_when: command.rc == 0

    - name: Edge WiFi - Generate WPA2 passphrase
      command: wpa_passphrase "{{ edge_local_wifi_name }}" "{{ edge_wifi_password }}"
      register: wpa_passphrase_result
      changed_when: command.rc == 0

    - name: Edge WiFi - Configure hostapd incl. wpa passphrase
      template:
        src: hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        mode: 0644
        vars:
          edge_wifi_adapter: "{{ edge_wifi_adapter }}"
          wpa_passphrase: "{{ wpa_passphrase_result.stdout }}"
          edge_local_wifi_name: "{{ edge_local_wifi_name }}"

    - name: Edge WiFi - Configure dnsmasq
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        mode: 0644
        vars:
          edge_wifi_adapter: "{{ edge_wifi_adapter }}"
          edge_wifi_ip_address: "{{ edge_wifi_ip_address }}"
          edge_wifi_dhcp_dns: "{{ edge_wifi_dhcp_dns }}"
          edge_wifi_dhcp_range: "{{ edge_wifi_dhcp_range }}"

    - name: Restart hostapd and dnsmasq
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - hostapd
        - dnsmasq

    - name: Enable hostapd and dnsmasq at boot
      service:
        name: "{{ item }}"
        enabled: true
      loop:
        - hostapd
        - dnsmasq

    - name: Firewall - Allow HTTP connections on Raspberry Pi
      command: ufw allow 80
      register: ufw_http_result
      changed_when: ufw_http_result.stdout != ""

    - name: Firewall - Allow HTTPS connections on Raspberry Pi
      command: ufw allow 443
      register: ufw_https_result
      changed_when: ufw_https_result.stdout != ""

    - name: Firewall - Block SSH traffic from USB WiFi
      command: ufw deny in on {{ edge_wifi_adapter }} to any port 22
      changed_when: command.rc == 0

    - name: Firewall - Enable ufw
      command: ufw --force enable
      changed_when: ufw_http_result.changed or ufw_https_result.changed

    - name: SSH - Restrict SSH access from USB WiFi
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "ListenAddress {{ main_wifi_ip_address }}"
        state: present

    - name: SSH - Enable connections from main WiFi
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "AllowUsers {{ lookup('env', 'USE_SSH_USER_NAME') }}@{{ main_wifi_ip_address }}"
        state: present
      notify:
        - Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
