---
- name: Ensure k3s pre-requisites are met
  import_playbook: bootstrap-machines.yaml

- name: Install k3s on master
  hosts: master
  become: true
  gather_facts: false
  # First, ensure the pre-requisites are met

  pre_tasks:
    # First, make sure the environment variable for SSH access to the nodes is present.
    - include_tasks: ../tasklib/checkuserenv-tasks.yaml

  tasks:
    - name: Include k3s configuration variables
      include_vars: ../config/k3s-cluster-config.yaml

    - name: Check if k3s is already installed
      command: command -v k3s
      register: k3s_installed
      changed_when: false
      failed_when: false

    - name: Get installed k3s version
      command: k3s --version
      register: installed_version
      changed_when: false
      failed_when: false
      when: k3s_installed.rc == 0

    - name: Download k3s installer
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Install k3s master
      command:
        cmd: /tmp/k3s_install.sh --flannel-backend=calico
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Get Node Token
      command:
        cmd: cat /var/lib/rancher/k3s/server/node-token
      register: master_node_token
      changed_when: false

    - name: Get kubeconfig
      command: cat /etc/rancher/k3s/k3s.yaml
      register: kubeconfig
      changed_when: false

    - name: Copy kubeconfig to local machine
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: "~/k3s_kubeconfig.yaml"
        mode: '0755'
      delegate_to: localhost

- name: Install k3s on agent nodes
  hosts: agents
  become: true
  gather_facts: true
  tasks:
    - name: Download k3s installer
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Install k3s agent
      command:
        cmd: /tmp/k3s_install.sh K3S_URL=https://{{ hostvars['master']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['master']['master_node_token'].stdout }}
        creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig

    - name: Ensure k3s service is running
      systemd:
        name: k3s
        state: started
