---
- name: Update Ubuntu machines
  hosts: all
  gather_facts: false
  become: yes
  remote_user: "{{ lookup('env', 'USE_SSH_USER_NAME') }}"
  tasks:
    - include_tasks: ../tasklib/upgrade-tasks.yaml

  # Loop over the hosts one by one such that on failure it stops, immediately
  serial: 1
  strategy: linear