Vagrant.configure("2") do |config|

  # Ubuntu 22.04 box for VirtualBox
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/ubuntu2204/versions/4.2.14/providers/virtualbox.box"
  config.vm.disk :disk, name: "osdisk", size: "30GB"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 3
  end

  # Use the default network switch
  config.vm.network "public_network", bridge: "Default Switch"

  # Update the OS after provisioning
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt upgrade -y
  SHELL

end